#!/usr/bin/python3

import sys
import json
from aiostream import core
import asyncio
import pathlib
import stat
import os
import shutil

path_arg = pathlib.Path("/arg")
path_wikilt = pathlib.Path("/wikilt")


@core.operator
async def reader():
    while True:
        line = await loop.run_in_executor(None, sys.stdin.readline)
        try:
            yield json.loads(line)
        except json.JSONDecodeError as e:
            print(e)
            return


async def run(cmd):
    proc = None

    try:
        await asyncio.sleep(0.1)
        print(f"#WI_NATIVE clear")

        proc = await asyncio.create_subprocess_exec(
            str(cmd),
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.STDOUT)

        while True:
            line = await proc.stdout.readline()
            if not line:
                # len(data) == 0 and proc.stdout.at_eof():
                break

            print(line.decode('utf8').rstrip(), flush=True)
    except asyncio.CancelledError:
        try:
            await proc.kill()
        except Exception:
            pass
    except Exception as e:
        msg = {'type': 'error', 'val': f"chyba {e!s}"}
        print(f"#WI_NATIVE {json.dumps(msg)}")

        try:
            await proc.kill()
        except Exception:
            pass
    finally:
        if proc is not None:
            await proc.wait()


def find_script(path):
    if path == path_wikilt:
        return

    with os.scandir(path) as it:
        for de in it:
            if de.is_file(follow_symlinks=False) and (
                    de.stat().st_mode & stat.S_IEXEC):
                return path/de.name


def find_files(reg, path):
    if os.path.isfile(path):
        if reg.match(str(path)):
            if not os.access(path, os.X_OK):
                os.chmod(path, 0o777)

            yield path
    else:
        for p in sorted(os.listdir(path)):
            for x in find_files(reg, path/p):
                yield x


async def main():
    run_task = find_script(pathlib.Path(os.environ.get("WI_HOME", "/wikilt")))

    t = None

    path_arg.mkdir(parents=True, exist_ok=True)

    async with core.streamcontext(reader()) as streamer:
        async for item in streamer:
            if item:
                n = item[0]
                arg = item[1]

                apath = path_arg/f"{n!s}.json"
                apath_d = path_arg/f"{n!s}"

                if arg is None:
                    try:
                        os.remove(apath)
                    except OSError:
                        pass
                else:
                    with open(apath, "w") as f:
                        f.write(json.dumps(item[1]))

                if os.path.exists(apath_d):
                    shutil.rmtree(apath_d)

            # apath_d = path_arg/f"arg{n!s}"
            # os.makedirs(apath_d, exist_ok=True)

            # if item[1] is None:
            #    try:
            #        os.remove(fn)
            #    except OSError:
            #        pass
            # elif 'type' in arg and arg['type'] == 'files':
            #    apath = path_arg/str(n)
#
#                os.makedirs(apath, exist_ok=True)
#                for i in arg['val']:
#                    with open(apath/i['name'], "wb") as f:
#                        f.write(base64.b64decode(i['content']))

            if t and not t.done():
                t.cancel()

            t = asyncio.ensure_future(run(run_task))

    if t:
        t.cancel()


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()
