#!/usr/bin/python3

import sys
import json
from aiostream import core
import asyncio
import pathlib
import stat
import os
import base64
import re

path_root = pathlib.Path("/i")
path_arg = pathlib.Path("/data/arg")

@core.operator
async def reader():
    while True:
        l = await loop.run_in_executor(None, sys.stdin.readline)

        try:
            yield json.loads(l)
        except json.JSONDecodeError as e:
            print(e)
            return


wi_native_re = re.compile(b"^[#]\s*WI[-_]NATIVE\s*(.*)")

async def run(cmds):
    out = list()


    for cmd in cmds:
        proc = None
        try:
            proc = await asyncio.create_subprocess_exec(str(cmd),
                                                        stdout=asyncio.subprocess.PIPE,
                                                        stderr=asyncio.subprocess.STDOUT)

            while True:
                data = await proc.stdout.readline()
                if len(data) == 0 and proc.stdout.at_eof():
                    break

                m = wi_native_re.match(data)
                if m:
                    print(m.group(1).decode('utf8'), flush=True)
                else:
                    data = data.decode('utf8').rstrip()
                    out.append(data)

                    print(json.dumps({'type':'stdout', 'val':"\n".join(out), 'new':data}), flush=True)

        except asyncio.CancelledError:
            if proc:
                proc.kill()

        except Exception as e:
            print(json.dumps({'type':'error', 'val':str(e)}), flush=True)
            if proc:
                proc.kill()
            raise

        finally:
            if proc:
                await proc.wait()


daemon_re = re.compile("^.*/daemon[^/]*$")
task_re = re.compile("^.*/task[^/]*$")

def find_files(reg, path=path_root):
    if os.path.isfile(path):
        if reg.match(str(path)):
            if not os.access(path, os.X_OK):
                os.chmod(path, 0o777)

            yield path
    else:
        for p in sorted(os.listdir(path)):
            for x in find_files(reg, path/p):
                yield x



async def main():
    """ Run tasks and communicate with wikilt.

    The message from (stdin) and to (stdout) wikilt must be json strings, one
    message per line.

    The tasks are files in /task/ and /daemon/ dirs, subdirs are ignored. All
    "tasks" and "daemons" are started in parallel.

    When a message arrives, the content of /arg/ is update accordingly.  Then
    the "daemons" are notified by empty line on stdin, the "tasks" are
    (re)started.


    """

    asyncio.ensure_future(run([x for x in find_files(daemon_re)]))

    t = None

    path_arg.mkdir(parents=True, exist_ok=True)

    async with core.streamcontext(reader()) as streamer:
        async for item in streamer:
            #with open("/aaa") as f:
            #    f.write(str(item))

            fn = path_arg/f"{item[0]}.json"

            if item[1] is None:
                try:
                    os.remove(fn)
                except OSError:
                    pass

            with open(fn, "w") as f:
                f.write(json.dumps(item[1]))

            #elif 'type' in arg and arg['type'] == 'files':
            #    apath = path_arg/str(n)
#
#                os.makedirs(apath, exist_ok=True)
#                for i in arg['val']:
#                    with open(apath/i['name'], "wb") as f:
#                        f.write(base64.b64decode(i['content']))

            if t and not t.done():
                t.cancel()

            t = asyncio.ensure_future(run([x for x in find_files(task_re)]))

    if t:
        t.cancel()


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()
