#!/usr/bin/env python3

import re
import sys
import wiki_inputs
import ipdb

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(wiki_inputs.main())

