#!/bin/bash

java_files=( $(find /data/unpack/ -maxdepth 1 -type f -name '*.java' 2>/dev/null) ) || exit 0

[[ -z "${java_files[@]}" ]] || { \
	echo "$ checkstyle ${java_files[@]#/data/unpack/}"
	out=$(java -jar /lib/checkstyle-8.5-all.jar -c /lib/style.xml "${java_files[@]}") || {
		out2=$(grep -v '^\(Starting\|Audit done\|Checkstyle ends\)' <<<"$out")
		head <<<"$out2"
		[[ $(wc -l <<<"$out2") -le 10 ]] || echo "..."
		exit 1
	}
}
