#!/bin/bash

java_files=( $(find /data/unpack/ -type f -name '*.java' -print) )

[[ -z "${java_files[@]}" ]] || { \
	echo "$ checkstyle ${java_files[@]#/data/unpack/}"
	out=$(java -jar /lib/checkstyle-8.5-all.jar -c /lib/style.xml "${java_files[@]}") || {
		grep -v '^\(Starting\|Audit done\|Checkstyle ends\)' <<<"$out"
		exit 1
	}
}
