#!/bin/bash

function jj { local IFS=":"; echo "$*"; }

function do_javac {
	jars=( $(find / -maxdepth 1 -type f -name '*.jar') )

	echo "$ javac " $([[ -z "${jars[@]}" ]] || echo "-classpath"  $(jj "${jars[@]#/}")) "${@#/data/unpack/}"

	javac $([[ -z $jars ]] || echo "-classpath" $(jj "${jars[@]}")) -encoding utf-8 -d /data/build $@ || exit 1

	for f in $(find /data/build -name '*.class' | sort)
	do
		if javap -public "$f" | grep -qF 'public static void main('
		then
			main=${f#/data/build/}
			main=${main%.class}
			echo "${main//\//.}" >> /data/.mainclass
		fi
	done
}

mkdir -p /data/build

java_files=( $(find /data/unpack/ -maxdepth 1 -type f -name '*.java' 2>/dev/null) ) || exit 0

[[ -z "$java_files" ]] || do_javac "${java_files[@]}"
