#!/usr/bin/python3

import json
import os
import re

re_fn = re.compile(r'.*unpack_(?P<arg>.*)(.py)?$')
tdir = "/data/unpack"
tdir2 = "/data/unpack_all"

if __name__ == "__main__":
    m = re_fn.match(os.path.basename(__file__))
    arg = m.group('arg') if m else 'arg0'

    with open(f"/data/{arg}.json") as f:
        data = json.load(f)

    if data:
        if not os.path.exists(tdir):
            os.makedirs(tdir)
        if not os.path.exists(tdir2):
            os.makedirs(tdir2)

        if 'type' in data and data['type'] == 'input':
            if 'others' in data:
                for k in data['others']:
                    t = os.path.join(tdir2, k)
                    data2 = data['others'][k]

                    if 'type' in data2 and data2['type'] == 'files':
                        if not os.path.exists(t):
                            os.makedirs(t)

                        for d in data2['val']:
                            if 'content' in d and 'name' in d:
                                with open(os.path.join(t,d['name']), "w") as f:
                                    f.write(d['content'])

            data = data['val']

        if 'type' in data and data['type'] in [ 'str', 'int' ]:
            with open(os.path.join(tdir,f"{arg}.txt"), "w") as f:
                if data['val'] is not None:
                    f.write(data['val'])

        if 'type' in data and data['type'] == 'files':
            for d in data['val']:
                if 'content' in d and 'name' in d:
                    with open(os.path.join(tdir,d['name']), "w") as f:
                        f.write(d['content'])

