#!/usr/bin/python

import json
import os
import re

re_fn = re.compile(r'.*unpack_(?P<arg>.*)(.py)?$')
tdir = "/data/unpack"

if __name__ == "__main__":
    m = re_fn.match(os.path.basename(__file__))
    arg = m.group('arg') if m else 'arg0'

    with open(f"/data/{arg}.json") as f:
        data = json.load(f)

    if not os.path.exists(tdir):
        os.makedirs(tdir)

    if data['type'] == 'input':
        data = data['val']

    if data['type'] == 'files':
        for d in data['val']:
            if 'content' in d and 'name' in d:
                with open(os.path.join(tdir,d['name']), "w") as f:
                    f.write(d['content'])


